acl_interfaces:
-   name: BVI10
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: Loopback100
-   name: Loopback1000
-   name: Loopback1234
-   name: Loopback234
-   name: Loopback400
-   name: Loopback555
-   name: Loopback9001
-   name: MgmtEth0/RP0/CPU0/0
-   name: TenGigE0/0/0/0
acls: []
bgp_address_family:
    address_family:
    -   afi: ipv4
        safi: unicast
    as_number: '65000'
bgp_global:
    as_number: '65000'
    bgp:
        router_id: 198.51.100.0
    neighbors:
    -   neighbor_address: 192.0.2.1
        remote_as: 65001
bgp_neighbor_address_family:
    as_number: '65000'
    neighbors:
    -   address_family:
        -   afi: ipv4
            route_policy:
                inbound: PERMIT-ALL
                outbound: PERMIT-ALL
            safi: unicast
        neighbor_address: 192.0.2.1
hostname: {}
interfaces:
-   description: '***TEST LOOPBACK****'
    enabled: true
    name: Loopback100
-   enabled: true
    name: Loopback234
-   enabled: true
    name: Loopback400
-   description: test gnmi set
    enabled: true
    name: Loopback555
-   description: '**2TEST 1000 LOOPBACK2****'
    enabled: true
    name: Loopback1000
-   enabled: true
    name: Loopback1234
-   enabled: true
    name: Loopback9001
-   enabled: true
    name: MgmtEth0/RP0/CPU0/0
-   description: '"test"'
    enabled: false
    name: GigabitEthernet0/0/0/0
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/1
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/2
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/3
-   enabled: false
    name: GigabitEthernet0/0/0/4
-   enabled: false
    name: GigabitEthernet0/0/0/5
-   enabled: false
    name: GigabitEthernet0/0/0/6
-   description: testssdfsdfg
    enabled: true
    name: TenGigE0/0/0/0
l2_interfaces:
-   name: Loopback100
-   name: Loopback234
-   name: Loopback400
-   name: Loopback555
-   name: Loopback1000
-   name: Loopback1234
-   name: Loopback9001
-   name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: TenGigE0/0/0/0
l3_interfaces:
-   ipv4:
    -   address: 1.1.1.100/32
    name: Loopback100
-   ipv4:
    -   address: 1.1.1.20/32
    name: Loopback234
-   name: Loopback400
-   name: Loopback555
-   ipv4:
    -   address: 2.2.2.200/32
    name: Loopback1000
-   ipv4:
    -   address: 192.168.100.1/24
    name: Loopback1234
-   ipv4:
    -   address: 10.0.0.110/16
    name: Loopback9001
-   ipv4:
    -   address: 10.10.20.175/24
    name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: TenGigE0/0/0/0
lacp: {}
lacp_interfaces:
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: TenGigE0/0/0/0
lag_interfaces: []
lldp_global: {}
lldp_interfaces:
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: TenGigE0/0/0/0
logging_global:
    monitor:
        severity: debugging
ntp_global:
    servers:
    -   prefer: true
        server: 132.163.97.5
ospfv3: {}
prefix_lists: []
snmp_server:
    communities:
    -   name: public
        ro: true
    traps:
        addrpool:
            high: true
            low: true
        bfd: true
        bgp:
            cbgp2: true
        bridgemib: true
        cisco_entity_ext: true
        config: true
        copy_complete: true
        diameter:
            peerdown: true
            peerup: true
            permanentfail: true
            protocolerror: true
            transientfail: true
        entity: true
        entity_redundancy:
            all: true
            status: true
            switchover: true
        entity_state:
            operstatus: true
            switchover: true
        flash:
            insertion: true
            removal: true
        fru_ctrl: true
        hsrp: true
        ipsec:
            start: true
            stop: true
        ipsla: true
        isakmp:
            start: true
            stop: true
        isis:
            all: true
        l2tun:
            sessions: true
            tunnel_down: true
            tunnel_up: true
        l2vpn:
            all: true
            vc_down: true
            vc_up: true
        msdp_peer_state_change: true
        ospf:
            errors:
                authentication_failure: true
                bad_packet: true
                config_error: true
                virt_authentication_failure: true
                virt_bad_packet: true
                virt_config_error: true
            lsa:
                lsa_maxage: true
                lsa_originate: true
            retransmit:
                packets: true
                virt_packets: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        ospfv3:
            errors:
                bad_packet: true
                config_error: true
                virt_bad_packet: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                restart_status_change: true
                restart_virtual_helper_status_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        pim:
            interface_state_change: true
            invalid_message_received: true
            neighbor_change: true
            rp_mapping_change: true
        power: true
        rf: true
        rsvp:
            all: true
            lost_flow: true
            new_flow: true
        selective_vrf_download_role_change: true
        sensor: true
        snmp:
            authentication: true
            coldstart: true
            linkdown: true
            linkup: true
            warmstart: true
        subscriber:
            session_agg_access_interface: true
            session_agg_node: true
        syslog: true
        system: true
        vpls:
            all: true
            full_clear: true
            full_raise: true
            status: true
        vrrp_events: true
static_routes: []
