acl_interfaces: {}
acls:
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 10
            source:
                address: 192.168.1.0
                wildcard_bits: 0.0.0.255
        acl_type: extended
        name: NAT-ACL
    -   aces:
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 10
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: '443'
            grant: permit
            protocol: tcp
            sequence: 20
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: udp
            sequence: 30
            source:
                any: true
        -   destination:
                any: true
            grant: deny
            log:
                set: true
            protocol: ip
            sequence: 40
            source:
                any: true
        acl_type: extended
        name: NETCONF_ACL
    -   aces:
        -   destination:
                host: 1.1.1.1
            grant: permit
            protocol: ip
            sequence: 10
            source:
                any: true
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: bgp
            grant: permit
            protocol: tcp
            sequence: 20
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: cmd
            grant: permit
            protocol: tcp
            sequence: 30
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: '123'
            grant: permit
            protocol: tcp
            sequence: 40
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: telnet
            grant: permit
            protocol: tcp
            sequence: 50
            source:
                host: 2.2.2.1
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 51
            source:
                host: 2.2.2.1
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: cmd
            grant: permit
            protocol: tcp
            sequence: 61
            source:
                host: 2.2.2.1
        acl_type: extended
        name: Test
    -   acl_type: extended
        name: meraki-fqdn-dns
    afi: ipv4
bgp_global:
    as_number: '65300'
    bgp:
        log_neighbor_changes: true
        router_id:
            address: 42.42.42.42
    neighbors:
    -   description: mysuperpeer
        neighbor_address: 40.40.40.40
        remote_as: '65200'
        timers:
            holdtime: 46
            interval: 15
        update_source: GigabitEthernet3
hostname:
    hostname: Cat8000V
interfaces:
-   description: MANAGEMENT INTERFACE - DON'T TOUCH ME
    enabled: true
    name: GigabitEthernet1
-   description: DEVNET_EXPERT
    enabled: true
    name: GigabitEthernet2
-   enabled: true
    name: GigabitEthernet3
-   enabled: true
    name: Loopback0
-   description: Created by Ansible
    enabled: true
    name: Loopback10
-   description: Loopback interface 100 created with Ansible
    enabled: true
    name: Loopback100
-   description: Added with RESTCONF
    enabled: true
    name: Loopback10055
-   enabled: true
    name: Loopback105
-   description: Configured by RESTCONF ga jadi
    enabled: true
    name: Loopback109
-   description: Demo interface by CLI and netmiko option
    enabled: true
    name: Loopback113
-   description: Loopback MV
    enabled: true
    name: Loopback159
-   description: Configured_with_Postman
    enabled: true
    name: Loopback200
-   enabled: true
    name: Loopback203
-   description: Krystianowy loopback
    enabled: true
    name: Loopback3100
-   description: Krystianowo Tomkowy loopback
    enabled: true
    name: Loopback3101
-   description: CREATED_BY_NETCONF
    enabled: true
    name: Loopback42
-   description: CONFIGURED_BY_NETMIKO
    enabled: true
    name: Loopback43
-   enabled: true
    name: Loopback55
-   description: Testing
    enabled: true
    name: Loopback56
-   enabled: true
    name: Loopback99
-   enabled: true
    name: VirtualPortGroup0
-   enabled: true
    name: Vlan1
l2_interfaces:
-   name: Loopback0
-   name: Loopback10
-   name: Loopback42
-   name: Loopback43
-   name: Loopback55
-   name: Loopback56
-   name: Loopback99
-   name: Loopback100
-   name: Loopback105
-   name: Loopback109
-   name: Loopback113
-   name: Loopback159
-   name: Loopback200
-   name: Loopback203
-   name: Loopback3100
-   name: Loopback3101
-   name: Loopback10055
-   name: VirtualPortGroup0
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
-   name: Vlan1
l3_interfaces:
-   ipv4:
    -   address: 10.10.20.48/24
    name: GigabitEthernet1
-   ipv4:
    -   address: 10.90.90.94/24
    name: GigabitEthernet2
-   name: GigabitEthernet3
-   ipv4:
    -   address: 10.0.0.1/24
    name: Loopback0
-   ipv4:
    -   address: 10.50.50.10/24
    name: Loopback10
-   ipv4:
    -   address: 10.10.10.10/32
    name: Loopback100
-   ipv4:
    -   address: 172.16.100.1/24
    name: Loopback10055
-   ipv4:
    -   address: 10.100.2.2/24
    name: Loopback105
-   ipv4:
    -   address: 10.255.255.9/24
    name: Loopback109
-   ipv4:
    -   address: 192.168.113.1/24
    name: Loopback113
-   ipv4:
    -   address: 159.159.159.159/32
    name: Loopback159
-   ipv4:
    -   address: 10.202.202.1/24
        secondary: true
    -   address: 10.200.2.2/24
    name: Loopback200
-   ipv4:
    -   address: 192.168.72.255/23
    name: Loopback203
-   ipv4:
    -   address: 1.2.3.15/32
    name: Loopback3100
-   ipv4:
    -   address: 1.2.3.16/32
    name: Loopback3101
-   ipv4:
    -   address: 10.0.42.5/24
    name: Loopback42
-   ipv4:
    -   address: 10.0.43.1/24
    name: Loopback43
-   ipv4:
    -   address: 10.101.75.1/24
    name: Loopback55
-   ipv4:
    -   address: 56.56.56.56/32
    name: Loopback56
-   ipv4:
    -   address: 10.101.99.9/24
    name: Loopback99
-   ipv4:
    -   address: 192.168.1.1/24
    name: VirtualPortGroup0
-   name: Vlan1
lacp:
    system:
        priority: 32768
lacp_interfaces:
-   name: loopback0
-   name: loopback10
-   name: loopback42
-   name: loopback43
-   name: loopback55
-   name: loopback56
-   name: loopback99
-   name: loopback100
-   name: loopback105
-   name: loopback109
-   name: loopback113
-   name: loopback159
-   name: loopback200
-   name: loopback203
-   name: loopback3100
-   name: loopback3101
-   name: loopback10055
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
-   name: Vlan1
lag_interfaces: {}
lldp_global: {}
lldp_interfaces: []
logging_global: {}
ntp_global:
    servers:
    -   server: ch.pool.ntp.org
ospfv2:
    processes:
    -   network:
        -   address: 10.200.2.2
            area: '200'
            wildcard_bits: 0.0.0.0
        -   address: 159.159.159.159
            area: '0'
            wildcard_bits: 0.0.0.0
        process_id: 10
        router_id: 159.159.159.159
    -   process_id: 19
        router_id: 33.44.88.22
    -   default_information:
            metric: 200
            originate: true
        network:
        -   address: 42.42.42.42
            area: '0'
            wildcard_bits: 0.0.0.0
        process_id: 42
        router_id: 42.42.42.42
prefix_lists:
-   afi: ipv4
    prefix_lists:
    -   entries:
        -   action: permit
            prefix: 10.0.1.0/24
            sequence: 10
        name: PL-STATIC-TO-OSPF
route_maps:
-   entries:
    -   action: permit
        match:
            interfaces:
            - Loopback42
        sequence: 10
    route_map: RM-CONN-TO-OSPF
-   entries:
    -   action: permit
        match:
            ip:
                address:
                    prefix_lists:
                    - PL-STATIC-TO-OSPF
        sequence: 10
    route_map: RM-STATIC-TO-OSPF
service:
    call_home: true
    counters: 0
    dhcp: true
    password_recovery: true
    private_config_encryption: true
    prompt: true
    slave_log: true
    timestamps:
    -   datetime_options:
            msec: true
        msg: debug
        timestamp: datetime
    -   datetime_options:
            msec: true
        msg: log
        timestamp: datetime
snmp_server:
    communities:
    -   name: cisco_lab
        rw: true
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
                interface: GigabitEthernet1
        -   dest: 10.19.19.20/32
            next_hops:
            -   forward_router_address: 10.100.1.1
vlans:
-   mtu: 1500
    name: default
    shutdown: disabled
    state: active
    vlan_id: 1
-   mtu: 1500
    name: fddi-default
    shutdown: enabled
    state: active
    vlan_id: 1002
-   mtu: 1500
    name: token-ring-default
    shutdown: enabled
    state: active
    vlan_id: 1003
-   mtu: 1500
    name: fddinet-default
    shutdown: enabled
    state: active
    vlan_id: 1004
-   mtu: 1500
    name: trnet-default
    shutdown: enabled
    state: active
    vlan_id: 1005
