acl_interfaces:
-   name: Bundle-Ether1
-   name: Bundle-Ether1.185
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: Loopback100
-   name: Loopback20
-   name: Loopback30
-   name: Loopback555
-   name: MgmtEth0/RP0/CPU0/0
acls: []
bgp_address_family:
    as_number: '151515'
bgp_global:
    as_number: '151515'
    vrfs:
    -   neighbors:
        -   neighbor_address: 15.15.15.15
        vrf: test
bgp_neighbor_address_family:
    as_number: '151515'
hostname:
    hostname: my_sweet_rtr
interfaces:
-   description: trunk ficticio
    enabled: true
    name: Bundle-Ether1
-   description: to-siman-l3vpn
    enabled: true
    name: Bundle-Ether1.185
-   description: msdp originator-id
    enabled: true
    name: Loopback20
-   description: anycast-RP
    enabled: true
    name: Loopback30
-   description: Ansible Edit 1
    enabled: true
    name: Loopback100
-   description: PRUEBA_KV
    enabled: true
    name: Loopback555
-   enabled: true
    name: MgmtEth0/RP0/CPU0/0
-   enabled: false
    name: GigabitEthernet0/0/0/0
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/1
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/2
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/3
-   enabled: false
    name: GigabitEthernet0/0/0/4
-   enabled: false
    name: GigabitEthernet0/0/0/5
-   enabled: false
    name: GigabitEthernet0/0/0/6
l2_interfaces:
-   name: Bundle-Ether1
-   encapsulation:
        dot1q: 185
    name: Bundle-Ether1.185
-   name: Loopback20
-   name: Loopback30
-   name: Loopback100
-   name: Loopback555
-   name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
l3_interfaces:
-   name: Bundle-Ether1
-   ipv4:
    -   address: 168.245.89.233/30
    name: Bundle-Ether1.185
-   ipv4:
    -   address: 85.42.175.126/32
    name: Loopback20
-   ipv4:
    -   address: 85.42.175.127/32
    name: Loopback30
-   ipv4:
    -   address: 1.1.1.100/32
    name: Loopback100
-   name: Loopback555
-   ipv4:
    -   address: 10.10.20.175/24
    name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
lacp: {}
lacp_interfaces:
-   name: Bundle-Ether1
-   name: Bundle-Ether1.185
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
lag_interfaces:
-   members:
    -   member: GigabitEthernet0/0/0/0
        mode: active
    -   member: GigabitEthernet0/0/0/1
        mode: active
    name: Bundle-Ether1
-   members:
    -   member: GigabitEthernet0/0/0/0
        mode: active
    -   member: GigabitEthernet0/0/0/1
        mode: active
    name: Bundle-Ether1
lldp_global: {}
lldp_interfaces:
-   name: Bundle-Ether1
-   name: Bundle-Ether1.185
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
logging_global: {}
ntp_global: {}
ospf_interfaces:
-   name: Loopback20
    type: loopback
-   name: Loopback30
    type: loopback
ospfv2:
    processes:
    -   process_id: '100'
ospfv3: {}
prefix_lists: []
snmp_server:
    communities:
    -   name: public
        ro: true
    traps:
        addrpool:
            high: true
            low: true
        bfd: true
        bgp:
            cbgp2: true
        bridgemib: true
        cisco_entity_ext: true
        config: true
        copy_complete: true
        diameter:
            peerdown: true
            peerup: true
            permanentfail: true
            protocolerror: true
            transientfail: true
        entity: true
        entity_redundancy:
            all: true
            status: true
            switchover: true
        entity_state:
            operstatus: true
            switchover: true
        flash:
            insertion: true
            removal: true
        fru_ctrl: true
        hsrp: true
        ipsec:
            start: true
            stop: true
        ipsla: true
        isakmp:
            start: true
            stop: true
        isis:
            all: true
        l2tun:
            sessions: true
            tunnel_down: true
            tunnel_up: true
        l2vpn:
            all: true
            vc_down: true
            vc_up: true
        msdp_peer_state_change: true
        ospf:
            errors:
                authentication_failure: true
                bad_packet: true
                config_error: true
                virt_authentication_failure: true
                virt_bad_packet: true
                virt_config_error: true
            lsa:
                lsa_maxage: true
                lsa_originate: true
            retransmit:
                packets: true
                virt_packets: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        ospfv3:
            errors:
                bad_packet: true
                config_error: true
                virt_bad_packet: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                restart_status_change: true
                restart_virtual_helper_status_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        pim:
            interface_state_change: true
            invalid_message_received: true
            neighbor_change: true
            rp_mapping_change: true
        power: true
        rf: true
        rsvp:
            all: true
            lost_flow: true
            new_flow: true
        selective_vrf_download_role_change: true
        sensor: true
        snmp:
            authentication: true
            coldstart: true
            linkdown: true
            linkup: true
            warmstart: true
        subscriber:
            session_agg_access_interface: true
            session_agg_node: true
        syslog: true
        system: true
        vpls:
            all: true
            full_clear: true
            full_raise: true
            status: true
        vrrp_events: true
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
            -   forward_router_address: 10.10.20.254
                interface: MgmtEth0
        safi: unicast
vrf_address_family:
-   name: test
vrf_global:
-   name: test
vrf_interfaces:
-   name: Bundle-Ether1
-   name: Bundle-Ether1.185
-   name: Loopback20
-   name: Loopback30
-   name: Loopback100
-   name: Loopback555
-   name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
