acl_interfaces: {}
acls: {}
bgp_global: {}
hostname:
    hostname: csr1000v-1
interfaces:
-   description: MANAGEMENT INTERFACE - DON'T TOUCH ME
    enabled: true
    name: GigabitEthernet1
-   description: Network Interface
    enabled: false
    name: GigabitEthernet2
-   description: Network Interface
    enabled: false
    name: GigabitEthernet3
-   description: my wesley's test ansible interface
    enabled: true
    name: Loopback11
-   description: my test ansible interface
    enabled: true
    name: Loopback17
-   description: my test ansible interface
    enabled: true
    name: Loopback30
-   description: my test ansible interface
    enabled: true
    name: Loopback55
-   description: my test ansible interface
    enabled: true
    name: Loopback741
l2_interfaces:
-   name: Loopback11
-   name: Loopback17
-   name: Loopback30
-   name: Loopback55
-   name: Loopback741
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
l3_interfaces:
-   ipv4:
    -   address: 10.10.20.48/24
    name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
-   name: Loopback11
-   ipv4:
    -   address: 192.168.17.17/24
    name: Loopback17
-   ipv4:
    -   address: 172.16.30.1/32
    name: Loopback30
-   ipv4:
    -   address: 172.16.3.229/24
    name: Loopback55
-   ipv4:
    -   address: 197.222.123.214/32
    name: Loopback741
lacp:
    system:
        priority: 32768
lacp_interfaces:
-   name: loopback11
-   name: loopback17
-   name: loopback30
-   name: loopback55
-   name: loopback741
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
lag_interfaces: {}
lldp_global: {}
lldp_interfaces: []
logging_global: {}
ntp_global: {}
ospfv2: {}
prefix_lists: {}
route_maps: {}
service:
    counters: 0
    dhcp: true
    pad: true
    password_recovery: true
    prompt: true
    slave_log: true
    timestamps:
    -   datetime_options:
            msec: true
        msg: debug
        timestamp: datetime
    -   datetime_options:
            msec: true
        msg: log
        timestamp: datetime
snmp_server: {}
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
                interface: GigabitEthernet1
