lacp:
    system:
        priority: 32768
lldp_interfaces: []
vlans:
-   mtu: 1500
    name: default
    shutdown: disabled
    state: active
    vlan_id: 1
-   mtu: 1500
    name: fddi-default
    shutdown: enabled
    state: active
    vlan_id: 1002
-   mtu: 1500
    name: token-ring-default
    shutdown: enabled
    state: active
    vlan_id: 1003
-   mtu: 1500
    name: fddinet-default
    shutdown: enabled
    state: active
    vlan_id: 1004
-   mtu: 1500
    name: trnet-default
    shutdown: enabled
    state: active
    vlan_id: 1005
