acl_interfaces:
-   name: Vlan1
-   name: Vlan100
-   name: Vlan101
-   name: Vlan102
-   name: Vlan103
-   name: Vlan104
-   name: Vlan105
-   name: Vlan110
-   name: Vlan120
-   name: Vlan992
-   name: port-channel11
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback1
-   name: loopback2
-   name: loopback10
-   name: loopback20
-   name: loopback24
-   name: loopback30
-   name: loopback35
-   name: loopback98
-   name: loopback99
acls: []
bfd_interfaces: []
bgp_address_family:
    address_family:
    -   afi: ipv4
        networks:
        -   prefix: 172.16.0.0/16
        safi: unicast
    as_number: '65535'
bgp_global:
    as_number: '65535'
    neighbors:
    -   neighbor_address: 172.16.0.2
        remote_as: '65535'
    router_id: 172.16.0.1
    timers:
        prefix_peer_timeout: 30
hostname:
    hostname: sbx-ao
hsrp_interfaces: []
interfaces:
-   name: Vlan1
-   description: mgmt svi - DEMO PLEASE DON'T TOUCH
    name: Vlan100
-   description: prod svi - DEMO PLEASE DON'T TOUCH
    name: Vlan101
-   description: dev svi - DEMO PLEASE DON'T TOUCH
    name: Vlan102
-   description: test svi - DEMO PLEASE DON'T TOUCH
    name: Vlan103
-   description: security svi - DEMO PLEASE DON'T TOUCH
    name: Vlan104
-   description: iot svi - DEMO PLEASE DON'T TOUCH
    name: Vlan105
-   name: Vlan110
-   enabled: true
    name: Vlan120
-   name: Vlan992
-   name: port-channel11
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   description: L3 Link
    mode: layer3
    name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   description: Ringcam
    name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   description: DO NOT TOUCH CONFIG ON THIS INTERFACE
    name: mgmt0
-   name: loopback1
-   name: loopback2
-   name: loopback10
-   name: loopback20
-   name: loopback24
-   description: My Learning Lab Loopback
    name: loopback30
-   name: loopback35
-   description: Configured using OpenConfig Model
    name: loopback98
-   description: Full intf config via NETCONF
    name: loopback99
l2_interfaces:
-   name: Vlan1
-   name: Vlan100
-   name: Vlan101
-   name: Vlan102
-   name: Vlan103
-   name: Vlan104
-   name: Vlan105
-   name: Vlan110
-   name: Vlan120
-   name: Vlan992
-   mode: trunk
    name: port-channel11
    trunk:
        allowed_vlans: 100-110
-   mode: trunk
    name: Ethernet1/1
    trunk:
        allowed_vlans: 100-110
-   mode: trunk
    name: Ethernet1/2
    trunk:
        allowed_vlans: 100-110
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   mode: trunk
    name: Ethernet1/64
-   name: mgmt0
-   name: loopback1
-   name: loopback2
-   name: loopback10
-   name: loopback20
-   name: loopback24
-   name: loopback30
-   name: loopback35
-   name: loopback98
-   name: loopback99
l3_interfaces:
-   name: Vlan1
-   ipv4:
    -   address: 172.16.100.1/24
    name: Vlan100
-   ipv4:
    -   address: 172.16.101.1/24
    name: Vlan101
-   ipv4:
    -   address: 172.16.102.1/24
    name: Vlan102
-   ipv4:
    -   address: 172.16.103.1/24
    name: Vlan103
-   ipv4:
    -   address: 172.16.104.1/24
    name: Vlan104
-   ipv4:
    -   address: 172.16.105.1/24
    name: Vlan105
-   ipv4:
    -   address: 192.168.0.1/24
    name: Vlan110
-   ipv4:
    -   address: 10.2.3.1/24
    name: Vlan120
-   ipv6:
    -   address: 2001:db8::218:baff:fed8:239d/30
    name: Vlan992
-   name: port-channel11
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   ipv4:
    -   address: 172.16.1.1/30
    name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   ipv4:
    -   address: 10.10.20.95/24
    name: mgmt0
-   ipv4:
    -   address: 172.16.0.1/32
    name: loopback1
-   ipv4:
    -   address: 2.2.2.2/32
    name: loopback2
-   ipv4:
    -   address: 10.10.10.10/32
    name: loopback10
-   ipv4:
    -   address: 20.20.20.20/32
    name: loopback20
-   ipv4:
    -   address: 24.24.24.24/32
    name: loopback24
-   name: loopback30
-   ipv4:
    -   address: 35.35.35.35/32
    name: loopback35
-   ipv4:
    -   address: 10.98.98.1/24
    name: loopback98
-   ipv4:
    -   address: 10.99.99.1/24
    name: loopback99
lacp: {}
lacp_interfaces: []
lag_interfaces:
-   members:
    -   member: Ethernet1/1
    -   member: Ethernet1/2
    name: port-channel11
lldp_global: {}
lldp_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
logging_global:
    console:
        state: disabled
ntp_global:
    authenticate: true
    authentication_keys:
    -   encryption: 7
        id: 1
        key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    peers:
    -   key_id: 1
        peer: 172.16.1.11
        vrf: management
    servers:
    -   server: 172.16.0.1
        vrf: default
    source_interface: mgmt0
ospf_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   address_family:
    -   afi: ipv4
        network: broadcast
        passive_interface: false
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: Vlan1
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan100
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan101
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan102
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan103
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan104
-   address_family:
    -   afi: ipv4
        processes:
        -   area:
                area_id: 0.0.0.0
            process_id: '1'
    name: Vlan105
-   name: Vlan110
-   name: Vlan120
-   name: Vlan992
-   name: loopback1
-   name: loopback10
-   name: loopback2
-   name: loopback20
-   name: loopback24
-   name: loopback30
-   name: loopback35
-   name: loopback98
-   name: loopback99
-   name: mgmt0
-   name: port-channel11
ospfv2: {}
ospfv3: {}
prefix_lists: []
route_maps: []
snmp_server:
    communities:
    -   group: network-operator
        name: DevNetSandboxReadSNMP
    -   group: network-admin
        name: DevNetSandboxWriteSNMP
    contact: DevNet-Sandbox
    location: Always-On-Sandbox
    source_interface:
        traps: mgmt0
    traps:
        aaa:
            server_state_change: true
        bridge:
            newroot: true
            topologychange: true
        callhome:
            event_notify: true
            smtp_send_fail: true
        cfs:
            merge_failure: true
            state_change_notif: true
        config:
            ccmCLIRunningConfigChanged: true
        feature_control:
            ciscoFeatOpStatusChange: true
        link:
            cisco_xcvr_mon_status_chg: true
        mmode:
            cseMaintModeChangeNotify: true
            cseNormalModeChangeNotify: true
        snmp:
            authentication: true
        stpx:
            inconsistency: true
            loop_inconsistency: true
            root_inconsistency: true
        sysmgr:
            cseFailSwCoreNotifyExtended: true
        system:
            clock_change_notification: true
        vtp:
            notifs: true
            vlancreate: true
            vlandelete: true
    users:
        auth:
        -   group: priv-15
            user: admin
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
    vrf: management
telemetry: {}
vlans:
-   enabled: true
    mode: ce
    name: default
    state: active
    vlan_id: 1
-   enabled: true
    mode: ce
    state: active
    vlan_id: 2
-   enabled: true
    mode: ce
    state: active
    vlan_id: 3
-   enabled: true
    mode: ce
    state: active
    vlan_id: 4
-   enabled: true
    mode: ce
    state: active
    vlan_id: 5
-   enabled: true
    mode: ce
    state: active
    vlan_id: 6
-   enabled: true
    mode: ce
    state: active
    vlan_id: 7
-   enabled: true
    mode: ce
    state: active
    vlan_id: 8
-   enabled: true
    mode: ce
    state: active
    vlan_id: 9
-   enabled: true
    mode: ce
    name: mgmt
    state: active
    vlan_id: 100
-   enabled: true
    mode: ce
    name: LL_VLAN_DEMO1
    state: active
    vlan_id: 101
-   enabled: true
    mode: ce
    name: dev
    state: active
    vlan_id: 102
-   enabled: true
    mode: ce
    name: test
    state: active
    vlan_id: 103
-   enabled: true
    mode: ce
    name: security
    state: active
    vlan_id: 104
-   enabled: true
    mode: ce
    name: iot
    state: active
    vlan_id: 105
-   enabled: true
    mode: ce
    state: active
    vlan_id: 111
-   enabled: true
    mode: ce
    name: krus
    state: active
    vlan_id: 120
