acl_interfaces:
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: Loopback100
-   name: Loopback1234
-   name: Loopback50
-   name: Loopback555
-   name: MgmtEth0/RP0/CPU0/0
acls:
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 10
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 20
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 30
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 40
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 50
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 60
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 70
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 80
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 90
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 100
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 110
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 120
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 130
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 140
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 150
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 160
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 170
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 180
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 190
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 200
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 210
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 220
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 230
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 240
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 250
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: domain
            grant: permit
            protocol: tcp
            sequence: 260
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 270
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: https
            grant: permit
            protocol: tcp
            sequence: 280
            source:
                any: true
        name: '100'
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            protocol_options:
                icmp:
                    echo_reply: true
            sequence: 10
            source:
                address: 10.10.2.0
                wildcard_bits: 0.0.0.255
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            protocol_options:
                icmp:
                    echo_reply: true
            sequence: 20
            source:
                address: 10.10.2.0
                wildcard_bits: 0.0.0.255
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            protocol_options:
                icmp:
                    echo_reply: true
            sequence: 30
            source:
                address: 10.10.2.0
                wildcard_bits: 0.0.0.255
        name: TEST_123
    -   aces:
        -   destination:
                address: 172.31.255.0
                wildcard_bits: 0.0.0.15
            grant: permit
            protocol: ipv4
            sequence: 10
            source:
                any: true
        -   destination:
                address: 172.31.255.16
                wildcard_bits: 0.0.0.15
            grant: permit
            protocol: ipv4
            sequence: 20
            source:
                any: true
        -   destination:
                address: 22.10.10.8
                wildcard_bits: 0.0.0.22
            grant: permit
            protocol: ipv4
            sequence: 40
            source:
                any: true
        -   destination:
                address: 22.10.10.2
                wildcard_bits: 0.0.0.24
            grant: permit
            protocol: ipv4
            sequence: 55
            source:
                any: true
        -   destination:
                address: 122.184.67.64
                wildcard_bits: 0.0.0.31
            grant: permit
            protocol: ipv4
            sequence: 65
            source:
                any: true
        name: WI-MAX-MANAGEMENT-BACKHAUL
    afi: ipv4
bgp_address_family:
    address_family:
    -   afi: ipv4
        networks:
        -   network: 1.1.1.100/32
        safi: unicast
    as_number: '65000'
bgp_global:
    as_number: '65000'
    neighbors:
    -   neighbor_address: 192.168.1.5
        remote_as: 65000
bgp_neighbor_address_family:
    as_number: '65000'
    neighbors:
    -   address_family:
        -   afi: ipv4
            safi: unicast
        neighbor_address: 192.168.1.5
hostname: {}
interfaces:
-   enabled: true
    name: Loopback50
-   description: '***TEST LOOPBACK****'
    enabled: true
    name: Loopback100
-   description: PRUEBA_KV
    enabled: true
    name: Loopback555
-   description: '***TEST LOOPBACK****'
    enabled: true
    name: Loopback1234
-   enabled: true
    name: MgmtEth0/RP0/CPU0/0
-   description: test
    enabled: true
    name: GigabitEthernet0/0/0/1
-   description: test
    enabled: true
    name: GigabitEthernet0/0/0/2
-   description: test
    enabled: true
    name: GigabitEthernet0/0/0/3
-   enabled: false
    name: GigabitEthernet0/0/0/5
-   enabled: false
    name: GigabitEthernet0/0/0/6
lacp: {}
lacp_interfaces:
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
lag_interfaces: []
lldp_global: {}
lldp_interfaces:
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
logging_global: {}
ntp_global: {}
ospf_interfaces: []
ospfv2:
    processes:
    -   process_id: '1'
ospfv3:
    processes:
    -   process_id: '1'
prefix_lists: []
snmp_server:
    communities:
    -   name: public
        ro: true
    traps:
        addrpool:
            high: true
            low: true
        bfd: true
        bgp:
            cbgp2: true
        bridgemib: true
        cisco_entity_ext: true
        config: true
        copy_complete: true
        diameter:
            peerdown: true
            peerup: true
            permanentfail: true
            protocolerror: true
            transientfail: true
        entity: true
        entity_redundancy:
            all: true
            status: true
            switchover: true
        entity_state:
            operstatus: true
            switchover: true
        flash:
            insertion: true
            removal: true
        fru_ctrl: true
        hsrp: true
        ipsec:
            start: true
            stop: true
        ipsla: true
        isakmp:
            start: true
            stop: true
        isis:
            all: true
        l2tun:
            sessions: true
            tunnel_down: true
            tunnel_up: true
        l2vpn:
            all: true
            vc_down: true
            vc_up: true
        msdp_peer_state_change: true
        ospf:
            errors:
                authentication_failure: true
                bad_packet: true
                config_error: true
                virt_authentication_failure: true
                virt_bad_packet: true
                virt_config_error: true
            lsa:
                lsa_maxage: true
                lsa_originate: true
            retransmit:
                packets: true
                virt_packets: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        ospfv3:
            errors:
                bad_packet: true
                config_error: true
                virt_bad_packet: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                restart_status_change: true
                restart_virtual_helper_status_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        pim:
            interface_state_change: true
            invalid_message_received: true
            neighbor_change: true
            rp_mapping_change: true
        power: true
        rf: true
        rsvp:
            all: true
            lost_flow: true
            new_flow: true
        selective_vrf_download_role_change: true
        sensor: true
        snmp:
            authentication: true
            coldstart: true
            linkdown: true
            linkup: true
            warmstart: true
        subscriber:
            session_agg_access_interface: true
            session_agg_node: true
        syslog: true
        system: true
        vpls:
            all: true
            full_clear: true
            full_raise: true
            status: true
        vrrp_events: true
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
            -   forward_router_address: 10.10.20.254
                interface: MgmtEth0
        safi: unicast
