acl_interfaces:
-   name: Vlan1
-   name: Vlan50
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback0
-   name: loopback5
-   name: loopback99
acls:
-   acls:
    -   name: ACL1
    afi: ipv4
bfd_interfaces:
-   bfd: enable
    echo: enable
    name: Vlan1
-   bfd: enable
    echo: enable
    name: Vlan50
-   bfd: enable
    echo: enable
    name: Ethernet1/1
-   bfd: enable
    echo: enable
    name: Ethernet1/2
-   bfd: enable
    echo: enable
    name: Ethernet1/3
-   bfd: enable
    echo: enable
    name: Ethernet1/4
-   bfd: enable
    echo: enable
    name: Ethernet1/5
-   bfd: enable
    echo: enable
    name: Ethernet1/6
-   bfd: enable
    echo: enable
    name: Ethernet1/7
-   bfd: enable
    echo: enable
    name: Ethernet1/8
-   bfd: enable
    echo: enable
    name: Ethernet1/9
-   bfd: enable
    echo: enable
    name: Ethernet1/10
-   bfd: enable
    echo: enable
    name: Ethernet1/11
-   bfd: enable
    echo: enable
    name: Ethernet1/12
-   bfd: enable
    echo: enable
    name: Ethernet1/13
-   bfd: enable
    echo: enable
    name: Ethernet1/14
-   bfd: enable
    echo: enable
    name: Ethernet1/15
-   bfd: enable
    echo: enable
    name: Ethernet1/16
-   bfd: enable
    echo: enable
    name: Ethernet1/17
-   bfd: enable
    echo: enable
    name: Ethernet1/18
-   bfd: enable
    echo: enable
    name: Ethernet1/19
-   bfd: enable
    echo: enable
    name: Ethernet1/20
-   bfd: enable
    echo: enable
    name: Ethernet1/21
-   bfd: enable
    echo: enable
    name: Ethernet1/22
-   bfd: enable
    echo: enable
    name: Ethernet1/23
-   bfd: enable
    echo: enable
    name: Ethernet1/24
-   bfd: enable
    echo: enable
    name: Ethernet1/25
-   bfd: enable
    echo: enable
    name: Ethernet1/26
-   bfd: enable
    echo: enable
    name: Ethernet1/27
-   bfd: enable
    echo: enable
    name: Ethernet1/28
-   bfd: enable
    echo: enable
    name: Ethernet1/29
-   bfd: enable
    echo: enable
    name: Ethernet1/30
-   bfd: enable
    echo: enable
    name: Ethernet1/31
-   bfd: enable
    echo: enable
    name: Ethernet1/32
-   bfd: enable
    echo: enable
    name: Ethernet1/33
-   bfd: enable
    echo: enable
    name: Ethernet1/34
-   bfd: enable
    echo: enable
    name: Ethernet1/35
-   bfd: enable
    echo: enable
    name: Ethernet1/36
-   bfd: enable
    echo: enable
    name: Ethernet1/37
-   bfd: enable
    echo: enable
    name: Ethernet1/38
-   bfd: enable
    echo: enable
    name: Ethernet1/39
-   bfd: enable
    echo: enable
    name: Ethernet1/40
-   bfd: enable
    echo: enable
    name: Ethernet1/41
-   bfd: enable
    echo: enable
    name: Ethernet1/42
-   bfd: enable
    echo: enable
    name: Ethernet1/43
-   bfd: enable
    echo: enable
    name: Ethernet1/44
-   bfd: enable
    echo: enable
    name: Ethernet1/45
-   bfd: enable
    echo: enable
    name: Ethernet1/46
-   bfd: enable
    echo: enable
    name: Ethernet1/47
-   bfd: enable
    echo: enable
    name: Ethernet1/48
-   bfd: enable
    echo: enable
    name: Ethernet1/49
-   bfd: enable
    echo: enable
    name: Ethernet1/50
-   bfd: enable
    echo: enable
    name: Ethernet1/51
-   bfd: enable
    echo: enable
    name: Ethernet1/52
-   bfd: enable
    echo: enable
    name: Ethernet1/53
-   bfd: enable
    echo: enable
    name: Ethernet1/54
-   bfd: enable
    echo: enable
    name: Ethernet1/55
-   bfd: enable
    echo: enable
    name: Ethernet1/56
-   bfd: enable
    echo: enable
    name: Ethernet1/57
-   bfd: enable
    echo: enable
    name: Ethernet1/58
-   bfd: enable
    echo: enable
    name: Ethernet1/59
-   bfd: enable
    echo: enable
    name: Ethernet1/60
-   bfd: enable
    echo: enable
    name: Ethernet1/61
-   bfd: enable
    echo: enable
    name: Ethernet1/62
-   bfd: enable
    echo: enable
    name: Ethernet1/63
-   bfd: enable
    echo: enable
    name: Ethernet1/64
-   bfd: enable
    echo: enable
    name: mgmt0
-   bfd: enable
    echo: enable
    name: loopback0
-   bfd: enable
    echo: enable
    name: loopback5
-   bfd: enable
    echo: enable
    name: loopback99
bgp_address_family: {}
bgp_global: {}
hostname: {}
hsrp_interfaces: []
interfaces:
-   name: Vlan1
-   name: Vlan50
-   description: test
    name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback0
-   name: loopback5
-   description: Full intf config via NETCONF
    name: loopback99
l2_interfaces:
-   name: Vlan1
-   name: Vlan50
-   mode: trunk
    name: Ethernet1/1
    trunk:
        allowed_vlans: 2100,2500
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback0
-   name: loopback5
-   name: loopback99
l3_interfaces:
-   name: Vlan1
-   ipv4:
    -   address: 10.255.251.2/24
    name: Vlan50
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   ipv4:
    -   address: 10.10.20.95/24
    name: mgmt0
-   ipv4:
    -   address: 10.10.10.1/24
    name: loopback0
-   ipv4:
    -   address: 10.10.15.1/24
    name: loopback5
-   ipv4:
    -   address: 10.99.99.1/24
    name: loopback99
lacp: {}
lacp_interfaces: []
lag_interfaces: []
lldp_global: {}
lldp_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
logging_global:
    console:
        state: disabled
ntp_global: {}
ospf_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: Vlan1
-   name: Vlan50
-   name: loopback0
-   name: loopback5
-   name: loopback99
-   name: mgmt0
ospfv2: {}
ospfv3: {}
prefix_lists: []
route_maps: []
snmp_server:
    users:
        auth:
        -   authentication:
                algorithm: md5
                localizedv2_key: true
                password: 52036704DA8793EDC8726140EB5216EDEA84
                priv:
                    aes_128: true
                    privacy_password: 37462F1D8084C3B9C47C4E72B94807AEF7D2
            group: network-admin
            user: admin
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
    vrf: management
telemetry: {}
vlans:
-   enabled: true
    mode: ce
    name: default
    state: active
    vlan_id: 1
-   enabled: true
    mode: ce
    name: Dev
    state: active
    vlan_id: 30
-   enabled: true
    mode: ce
    state: active
    vlan_id: 50
-   enabled: true
    mode: ce
    name: WIFI
    state: active
    vlan_id: 100
-   enabled: true
    mode: ce
    name: Mgmt
    state: active
    vlan_id: 101
