acl_interfaces:
-   name: Vlan1
-   name: Vlan100
-   name: Vlan2500
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback1
-   name: loopback2
-   name: loopback3
-   name: loopback5
-   name: loopback99
-   name: loopback555
acls:
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 10
            source:
                host: 172.30.13.23
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 20
            source:
                address: 172.30.191.0
                wildcard_bits: 0.0.0.255
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 30
            source:
                host: 172.30.56.146
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 40
            source:
                host: 172.30.56.149
        name: SNMP
    -   aces:
        -   destination:
                host: 172.18.2.55
            grant: permit
            protocol: tcp
            sequence: 10
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: '443'
            grant: permit
            protocol: tcp
            sequence: 20
            source:
                any: true
        name: test1
    afi: ipv4
bfd_interfaces: []
bgp_address_family: {}
bgp_global: {}
hostname:
    hostname: nxos
hsrp_interfaces: []
interfaces:
-   name: Vlan1
-   enabled: true
    name: Vlan100
-   enabled: true
    name: Vlan2500
-   description: test
    name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   description: The Cisco Switch Updated Config July
    name: Ethernet1/14
-   description: My Description-1
    name: Ethernet1/15
-   description: My Description
    name: Ethernet1/16
-   description: My Description-3
    name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   mode: layer3
    name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   description: lp0-mz
    name: loopback1
-   name: loopback2
-   name: loopback3
-   name: loopback5
-   description: Full intf config via NETCONF
    name: loopback99
-   name: loopback555
l2_interfaces:
-   name: Vlan1
-   name: Vlan100
-   name: Vlan2500
-   access:
        vlan: 100
    name: Ethernet1/1
    trunk:
        allowed_vlans: 1-10,12-138,140-4094
-   access:
        vlan: 200
    name: Ethernet1/2
    trunk:
        allowed_vlans: 1-10,12-138,140-4094
-   access:
        vlan: 100
    name: Ethernet1/3
    trunk:
        allowed_vlans: 1-10,12-138,140-4094
-   access:
        vlan: 1234
    mode: trunk
    name: Ethernet1/4
    trunk:
        allowed_vlans: '2500'
-   access:
        vlan: 100
    name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   mode: trunk
    name: Ethernet1/15
    trunk:
        allowed_vlans: 500-501,503-505
-   mode: trunk
    name: Ethernet1/16
    trunk:
        allowed_vlans: 500-501,503-505
-   mode: trunk
    name: Ethernet1/17
    trunk:
        allowed_vlans: 500-501,503-505
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
-   name: loopback1
-   name: loopback2
-   name: loopback3
-   name: loopback5
-   name: loopback99
-   name: loopback555
l3_interfaces:
-   name: Vlan1
-   ipv4:
    -   address: 10.100.200.1/24
    ipv6_redirects: false
    name: Vlan100
    redirects: false
-   ipv4:
    -   address: 172.16.232.1/29
    ipv6_redirects: false
    name: Vlan2500
    redirects: false
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   ipv6_redirects: false
    name: Ethernet1/60
    redirects: false
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   ipv4:
    -   address: 10.10.20.95/24
    name: mgmt0
-   ipv4:
    -   address: 10.10.10.22/32
    name: loopback1
-   ipv4:
    -   address: 2.2.2.2/32
    name: loopback2
-   ipv4:
    -   address: 3.3.3.3/32
    name: loopback3
-   name: loopback5
-   ipv4:
    -   address: 10.99.99.1/24
    name: loopback99
-   name: loopback555
lacp: {}
lacp_interfaces: []
lag_interfaces: []
lldp_global: {}
lldp_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: mgmt0
logging_global:
    console:
        state: disabled
ntp_global: {}
ospf_interfaces:
-   name: Ethernet1/1
-   name: Ethernet1/2
-   name: Ethernet1/3
-   name: Ethernet1/4
-   name: Ethernet1/5
-   name: Ethernet1/6
-   name: Ethernet1/7
-   name: Ethernet1/8
-   name: Ethernet1/9
-   name: Ethernet1/10
-   name: Ethernet1/11
-   name: Ethernet1/12
-   name: Ethernet1/13
-   name: Ethernet1/14
-   name: Ethernet1/15
-   name: Ethernet1/16
-   name: Ethernet1/17
-   name: Ethernet1/18
-   name: Ethernet1/19
-   name: Ethernet1/20
-   name: Ethernet1/21
-   name: Ethernet1/22
-   name: Ethernet1/23
-   name: Ethernet1/24
-   name: Ethernet1/25
-   name: Ethernet1/26
-   name: Ethernet1/27
-   name: Ethernet1/28
-   name: Ethernet1/29
-   name: Ethernet1/30
-   name: Ethernet1/31
-   name: Ethernet1/32
-   name: Ethernet1/33
-   name: Ethernet1/34
-   name: Ethernet1/35
-   name: Ethernet1/36
-   name: Ethernet1/37
-   name: Ethernet1/38
-   name: Ethernet1/39
-   name: Ethernet1/40
-   name: Ethernet1/41
-   name: Ethernet1/42
-   name: Ethernet1/43
-   name: Ethernet1/44
-   name: Ethernet1/45
-   name: Ethernet1/46
-   name: Ethernet1/47
-   name: Ethernet1/48
-   name: Ethernet1/49
-   name: Ethernet1/50
-   name: Ethernet1/51
-   name: Ethernet1/52
-   name: Ethernet1/53
-   name: Ethernet1/54
-   name: Ethernet1/55
-   name: Ethernet1/56
-   name: Ethernet1/57
-   name: Ethernet1/58
-   name: Ethernet1/59
-   address_family:
    -   afi: ipv4
        authentication:
            message_digest: true
        passive_interface: true
    name: Ethernet1/60
-   name: Ethernet1/61
-   name: Ethernet1/62
-   name: Ethernet1/63
-   name: Ethernet1/64
-   name: Vlan1
-   name: Vlan100
-   name: Vlan2500
-   name: loopback1
-   name: loopback2
-   name: loopback3
-   name: loopback5
-   name: loopback555
-   name: loopback99
-   name: mgmt0
ospfv2:
    processes:
    -   process_id: '5'
ospfv3: {}
prefix_lists: []
route_maps: []
snmp_server:
    communities:
    -   group: network-operator
        name: public
    -   group: network-operator
        name: testcommunity
    users:
        auth:
        -   authentication:
                algorithm: md5
                localizedv2_key: true
                password: 52036704DA8793EDC8726140EB5216EDEA84
                priv:
                    aes_128: true
                    privacy_password: 37462F1D8084C3B9C47C4E72B94807AEF7D2
            group: network-admin
            user: admin
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 192.168.1.254
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
    vrf: management
telemetry: {}
vlans:
-   enabled: true
    mode: ce
    name: default
    state: active
    vlan_id: 1
-   enabled: true
    mapped_vni: 1010201
    mode: ce
    name: vlan-201
    state: active
    vlan_id: 201
