acl_interfaces:
-   name: Bundle-Ether6
-   name: Bundle-Ether6.6477
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
-   name: Loopback0
-   name: Loopback1
-   name: Loopback10
-   name: Loopback2
-   name: Loopback4
-   name: Loopback6
-   name: MgmtEth0/RP0/CPU0/0
-   name: tunnel-ip3
acls: []
bgp_address_family:
    address_family:
    -   afi: ipv4
        safi: unicast
    as_number: '1234'
bgp_global:
    as_number: '1234'
    bgp:
        router_id: 1.1.1.1
    neighbors:
    -   neighbor_address: 1.1.1.2
        remote_as: 5555
bgp_neighbor_address_family:
    as_number: '1234'
    neighbors:
    -   address_family:
        -   afi: ipv4
            route_policy:
                inbound: allowedall
                outbound: allowedall
            safi: unicast
        neighbor_address: 1.1.1.2
hostname:
    hostname: Test123
interfaces:
-   description: '#test#'
    enabled: true
    name: Bundle-Ether6
-   description: SBI-ML3-3-184671-AKC-4096k-STATE-BANK-OF-INDIA-3-4651111-30102023
    enabled: true
    name: Bundle-Ether6.6477
-   description: Loopback Interface
    enabled: true
    name: Loopback0
-   enabled: true
    name: Loopback1
-   enabled: true
    name: Loopback2
-   enabled: true
    name: Loopback4
-   enabled: true
    name: Loopback6
-   enabled: true
    name: Loopback10
-   enabled: true
    name: MgmtEth0/RP0/CPU0/0
-   enabled: false
    name: GigabitEthernet0/0/0/0
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/1
-   description: '#test#'
    enabled: true
    name: GigabitEthernet0/0/0/2
-   description: test
    enabled: false
    name: GigabitEthernet0/0/0/3
-   enabled: false
    name: GigabitEthernet0/0/0/4
-   enabled: false
    name: GigabitEthernet0/0/0/5
-   enabled: false
    name: GigabitEthernet0/0/0/6
l2_interfaces:
-   name: Bundle-Ether6
-   encapsulation:
        dot1q: 1000
        second_dot1q: 502
    name: Bundle-Ether6.6477
-   name: Loopback0
-   name: Loopback1
-   name: Loopback2
-   name: Loopback4
-   name: Loopback6
-   name: Loopback10
-   name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
l3_interfaces:
-   name: Bundle-Ether6
-   ipv4:
    -   address: 10.171.221.134/30
    name: Bundle-Ether6.6477
-   ipv4:
    -   address: 192.0.2.1/32
    name: Loopback0
-   name: Loopback1
-   name: Loopback2
-   name: Loopback4
-   name: Loopback6
-   ipv4:
    -   address: 192.168.10.1/32
    name: Loopback10
-   ipv4:
    -   address: 10.10.20.175/24
    name: MgmtEth0/RP0/CPU0/0
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
lacp: {}
lacp_interfaces:
-   name: Bundle-Ether6
-   name: Bundle-Ether6.6477
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
lag_interfaces:
-   members:
    -   member: GigabitEthernet0/0/0/2
        mode: active
    name: Bundle-Ether6
-   members:
    -   member: GigabitEthernet0/0/0/2
        mode: active
    name: Bundle-Ether6
lldp_global: {}
lldp_interfaces:
-   name: Bundle-Ether6
-   name: Bundle-Ether6.6477
-   name: GigabitEthernet0/0/0/0
-   name: GigabitEthernet0/0/0/1
-   name: GigabitEthernet0/0/0/2
-   name: GigabitEthernet0/0/0/3
-   name: GigabitEthernet0/0/0/4
-   name: GigabitEthernet0/0/0/5
-   name: GigabitEthernet0/0/0/6
logging_global:
    buffered:
        severity: informational
ntp_global: {}
ospf_interfaces: []
ospfv2: {}
ospfv3: {}
prefix_lists: []
snmp_server:
    communities:
    -   name: public
        ro: true
    traps:
        addrpool:
            high: true
            low: true
        bfd: true
        bgp:
            cbgp2: true
        bridgemib: true
        cisco_entity_ext: true
        config: true
        copy_complete: true
        diameter:
            peerdown: true
            peerup: true
            permanentfail: true
            protocolerror: true
            transientfail: true
        entity: true
        entity_redundancy:
            all: true
            status: true
            switchover: true
        entity_state:
            operstatus: true
            switchover: true
        flash:
            insertion: true
            removal: true
        fru_ctrl: true
        hsrp: true
        ipsec:
            start: true
            stop: true
        ipsla: true
        isakmp:
            start: true
            stop: true
        isis:
            all: true
        l2tun:
            sessions: true
            tunnel_down: true
            tunnel_up: true
        l2vpn:
            all: true
            vc_down: true
            vc_up: true
        msdp_peer_state_change: true
        ospf:
            errors:
                authentication_failure: true
                bad_packet: true
                config_error: true
                virt_authentication_failure: true
                virt_bad_packet: true
                virt_config_error: true
            lsa:
                lsa_maxage: true
                lsa_originate: true
            retransmit:
                packets: true
                virt_packets: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        ospfv3:
            errors:
                bad_packet: true
                config_error: true
                virt_bad_packet: true
            state_change:
                if_state_change: true
                neighbor_state_change: true
                restart_status_change: true
                restart_virtual_helper_status_change: true
                virtif_state_change: true
                virtneighbor_state_change: true
        pim:
            interface_state_change: true
            invalid_message_received: true
            neighbor_change: true
            rp_mapping_change: true
        power: true
        rf: true
        rsvp:
            all: true
            lost_flow: true
            new_flow: true
        selective_vrf_download_role_change: true
        sensor: true
        snmp:
            authentication: true
            coldstart: true
            linkdown: true
            linkup: true
            warmstart: true
        subscriber:
            session_agg_access_interface: true
            session_agg_node: true
        syslog: true
        system: true
        vpls:
            all: true
            full_clear: true
            full_raise: true
            status: true
        vrrp_events: true
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
            -   forward_router_address: 10.10.20.254
                interface: MgmtEth0
        -   dest: 222.228.1.1/32
            next_hops:
            -   description: ddos-2024/10/19-stage2
                interface: Null0
                tag: 9999
        safi: unicast
