acl_interfaces: {}
acls: {}
bgp_global: {}
hostname:
    hostname: csr1000v-1
interfaces:
-   enabled: true
    name: BDI10
-   description: MANAGEMENT INTERFACE - DON'T TOUCH ME
    enabled: true
    name: GigabitEthernet1
-   description: Network Interface
    enabled: false
    name: GigabitEthernet2
-   description: Ringcam
    enabled: true
    name: GigabitEthernet3
-   enabled: true
    name: Loopback10
-   description: UPDATED from PUT23
    enabled: true
    name: Loopback1000
-   description: UPDATED from PUT23
    enabled: true
    name: Loopback1001
-   description: Agregada by Teslag Networks
    enabled: true
    name: Loopback401
l2_interfaces:
-   name: Loopback10
-   name: Loopback401
-   name: Loopback1000
-   name: Loopback1001
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
-   name: BDI10
l3_interfaces:
-   ipv4:
    -   address: 192.168.1.1/24
    name: BDI10
-   ipv4:
    -   address: 10.10.20.48/24
    name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
-   name: Loopback10
-   name: Loopback1000
-   name: Loopback1001
-   ipv4:
    -   address: 1.1.1.1/32
    name: Loopback401
lacp:
    system:
        priority: 32768
lacp_interfaces:
-   name: loopback10
-   name: loopback401
-   name: loopback1000
-   name: loopback1001
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
lag_interfaces: {}
lldp_global: {}
lldp_interfaces: []
logging_global: {}
ntp_global: {}
ospfv2:
    processes:
    -   passive_interfaces:
            interface:
                name:
                - Loopback401
                set_interface: true
        process_id: 1
        router_id: 1.1.1.1
prefix_lists: {}
route_maps: {}
service:
    counters: 0
    dhcp: true
    pad: true
    password_recovery: true
    prompt: true
    slave_log: true
    timestamps:
    -   datetime_options:
            msec: true
        msg: debug
        timestamp: datetime
    -   datetime_options:
            msec: true
        msg: log
        timestamp: datetime
snmp_server: {}
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
                interface: GigabitEthernet1
