acl_interfaces: {}
acls:
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 10
            source:
                address: 192.168.1.0
                wildcard_bits: 0.0.0.255
        acl_type: extended
        name: NAT-ACL
    -   aces:
        -   destination:
                host: 1.1.1.1
            grant: permit
            protocol: ip
            sequence: 10
            source:
                any: true
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: bgp
            grant: permit
            protocol: tcp
            sequence: 20
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: cmd
            grant: permit
            protocol: tcp
            sequence: 30
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.3
                port_protocol:
                    eq: '123'
            grant: permit
            protocol: tcp
            sequence: 40
            source:
                host: 2.2.2.2
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: telnet
            grant: permit
            protocol: tcp
            sequence: 50
            source:
                host: 2.2.2.1
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: www
            grant: permit
            protocol: tcp
            sequence: 51
            source:
                host: 2.2.2.1
        -   destination:
                host: 3.3.3.1
                port_protocol:
                    eq: cmd
            grant: permit
            protocol: tcp
            sequence: 61
            source:
                host: 2.2.2.1
        acl_type: extended
        name: Test
    -   acl_type: extended
        name: meraki-fqdn-dns
    afi: ipv4
bgp_global: {}
hostname:
    hostname: Cat8000V
interfaces:
-   description: MANAGEMENT INTERFACE - DON'T TOUCH ME
    enabled: true
    name: GigabitEthernet1
-   description: Network Interface
    enabled: true
    name: GigabitEthernet2
-   description: Network Interface
    enabled: false
    name: GigabitEthernet3
-   enabled: true
    name: Loopback0
-   enabled: true
    name: Loopback10
-   description: Loopback interface 100 created with Ansible
    enabled: true
    name: Loopback100
-   description: Added with RESTCONF
    enabled: true
    name: Loopback10055
-   enabled: true
    name: Loopback105
-   description: Configured by RESTCONF ga jadi
    enabled: true
    name: Loopback109
-   enabled: false
    name: Loopback159
-   description: Configured_with_Postman
    enabled: true
    name: Loopback200
-   enabled: true
    name: Loopback55
-   description: Testing
    enabled: true
    name: Loopback56
-   enabled: true
    name: Loopback99
-   enabled: true
    name: VirtualPortGroup0
l2_interfaces:
-   name: Loopback0
-   name: Loopback10
-   name: Loopback55
-   name: Loopback56
-   name: Loopback99
-   name: Loopback100
-   name: Loopback105
-   name: Loopback109
-   name: Loopback159
-   name: Loopback200
-   name: Loopback10055
-   name: VirtualPortGroup0
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
l3_interfaces:
-   ipv4:
    -   address: 10.10.20.48/24
    name: GigabitEthernet1
-   ipv4:
    -   address: 10.90.89.89/24
        secondary: true
    -   address: 10.90.90.90/24
    name: GigabitEthernet2
-   name: GigabitEthernet3
-   ipv4:
    -   address: 10.0.0.1/24
    name: Loopback0
-   name: Loopback10
-   ipv4:
    -   address: 10.10.10.10/32
    name: Loopback100
-   ipv4:
    -   address: 172.16.100.1/24
    name: Loopback10055
-   ipv4:
    -   address: 10.100.2.2/24
    name: Loopback105
-   ipv4:
    -   address: 10.255.255.9/24
    name: Loopback109
-   name: Loopback159
-   ipv4:
    -   address: 10.202.202.1/24
        secondary: true
    -   address: 10.200.2.2/24
    name: Loopback200
-   ipv4:
    -   address: 10.101.75.1/24
    name: Loopback55
-   ipv4:
    -   address: 56.56.56.56/32
    name: Loopback56
-   ipv4:
    -   address: 10.101.99.9/24
    name: Loopback99
-   ipv4:
    -   address: 192.168.1.1/24
    name: VirtualPortGroup0
lacp:
    system:
        priority: 32768
lacp_interfaces:
-   name: loopback0
-   name: loopback10
-   name: loopback55
-   name: loopback56
-   name: loopback99
-   name: loopback100
-   name: loopback105
-   name: loopback109
-   name: loopback159
-   name: loopback200
-   name: loopback10055
-   name: GigabitEthernet1
-   name: GigabitEthernet2
-   name: GigabitEthernet3
lag_interfaces: {}
lldp_global: {}
lldp_interfaces: []
logging_global: {}
ntp_global: {}
ospfv2:
    processes:
    -   process_id: 19
        router_id: 33.44.88.22
prefix_lists: {}
route_maps: {}
service:
    call_home: true
    counters: 0
    dhcp: true
    password_recovery: true
    private_config_encryption: true
    prompt: true
    slave_log: true
    timestamps:
    -   datetime_options:
            msec: true
        msg: debug
        timestamp: datetime
    -   datetime_options:
            msec: true
        msg: log
        timestamp: datetime
snmp_server:
    communities:
    -   name: cisco_lab
        rw: true
static_routes:
-   address_families:
    -   afi: ipv4
        routes:
        -   dest: 0.0.0.0/0
            next_hops:
            -   forward_router_address: 10.10.20.254
                interface: GigabitEthernet1
        -   dest: 10.19.19.20/32
            next_hops:
            -   forward_router_address: 10.100.1.1
vlans:
-   mtu: 1500
    name: default
    shutdown: disabled
    state: active
    vlan_id: 1
-   mtu: 1500
    name: fddi-default
    shutdown: enabled
    state: active
    vlan_id: 1002
-   mtu: 1500
    name: token-ring-default
    shutdown: enabled
    state: active
    vlan_id: 1003
-   mtu: 1500
    name: fddinet-default
    shutdown: enabled
    state: active
    vlan_id: 1004
-   mtu: 1500
    name: trnet-default
    shutdown: enabled
    state: active
    vlan_id: 1005
