name: network-config-as-code-pull-request
run-name: ${{ github.actor }} configure network devices (PR)
on:
  push:
    branches:
      - master

jobs:
  apply_network_configurations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: configs/*.config.yml

      - name: List all changed files
        id: extract-hosts
        run: |
          hosts=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            hosts+=(${file:8:-11})
          done
          num_hosts=$(echo $hosts | jq '. | length')
          echo "::set-output name=target_hosts::$hosts"
          echo "::set-output name=num_hosts::$num_hosts"

      - name: Launch Job Template
        id: launch_job
        if: steps.extract-hosts.outputs.num_hosts > 0
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://controller.autodotes.com/api/v2/job_templates/84/launch/'
          method: 'POST'
          bearerToken: ${{ secrets.AAP_TOKEN }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"extra_vars": {"_hosts": "${{ join(steps.extract-hosts.outputs.target_hosts) }}", "config_repo_name": "ansible-network-configs"}}'
    
      - name: Show Response
        if: steps.launch_job.conclusion == 'success'
        run: |
          echo ${{ steps.launch_job.outputs.response }}
          echo ${{ steps.launch_job.outputs.headers }}